image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  # https://developer.android.com/studio/ -> Command line tools only
  ANDROID_SDK_TOOLS: "4333796"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - build
  - test
  - release

assembleOss:
  stage: build
  script:
    - ./gradlew assembleOssDebug

assembleFit:
  stage: build
  script:
  - ./gradlew assembleGoogleFitDebug

checks:
  stage: test
  script:
  - ./gradlew check -PisCiBuild

assembleOssRelease:
  stage: release
  script:
  - echo $KEYSTORE_FILE | base64 -d > gitlab.keystore
  - ./gradlew assembleOssRelease
    -Pandroid.injected.signign.store.file=gitlab.keystore
    -Pandroid.injected.signing.key.alias=$KEY_ALIAS
    -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
  artifacts:
    paths:
    - app/oss/release/app-oss-release.apk
    - app/build/outputs/mapping/r8/oss/release/mapping.txt